app:
  name: "go-web-app"
  version: "1.0.0"
  key: "a-long-string-with-32-characters"

http:
  debug: true
  address: ":3000"
  headerLimit: 4096

database:
  debug: true
  host: "localhost"
  port: 5432
  user: "root"
  password: ""
